import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BadgeCheck, ChevronDown, Clock3, History, LogIn, Menu, Minus, Moon, PackageCheck, Plus, Search, ShieldCheck, ShoppingBag, Sprout, Sun, Truck, UserRound, X } from 'lucide-react'
import logo from './assets/logo.png'
import founderImage from './assets/dna.jpeg'
import './App.css'
import './theme-overrides.css'
import './light-mode-contrast.css'

const crops = {
  'Fresh Red Pepper': { rate: 0.15, days: 7, fee: 180 },
  'White Corn': { rate: 0.32, days: 14, fee: 120 },
  'Unripe Plantain': { rate: 0.25, days: 10, fee: 150 },
  Cassava: { rate: 0.28, days: 12, fee: 110 },
}

const products = [
  { id: 1, name: 'Organic Dried Pepper Flakes', short: 'Dried pepper', category: 'Spice', price: 4200, badge: 'High Vitamin C', art: 'pepper' },
  { id: 2, name: 'Pure Corn Pap Powder', short: 'Corn pap', category: 'Staple', price: 2800, badge: '12 Month Shelf-Life', art: 'corn' },
  { id: 3, name: 'Low-GI Plantain Flour', short: 'Plantain flour', category: 'Fitness', price: 3600, badge: 'Low Glycemic', art: 'plantain' },
]

function App() {
  const [page, setPage] = useState(window.location.pathname)
  const [theme, setTheme] = useState(localStorage.getItem('diet-planet-theme') || 'dark')
  const [farmer, setFarmer] = useState(JSON.parse(localStorage.getItem('diet-planet-farmer') || 'null'))
  const [authOpen, setAuthOpen] = useState(false)
  const [authMode, setAuthMode] = useState('login')
  const [authForm, setAuthForm] = useState({ name: '', phone: '', password: '' })
  const [orderHistory, setOrderHistory] = useState([])
  const [mobileOpen, setMobileOpen] = useState(false)
  const [crop, setCrop] = useState('Fresh Red Pepper')
  const [mass, setMass] = useState(100)
  const [settlement, setSettlement] = useState('split')
  const [location, setLocation] = useState('Lagos Processing Hub')
  const [batchId, setBatchId] = useState('DP-8829')
  const [cart, setCart] = useState([])
  const [cartOpen, setCartOpen] = useState(false)
  const [toast, setToast] = useState('')
  useEffect(() => {
    document.documentElement.dataset.theme = theme
    localStorage.setItem('diet-planet-theme', theme)
  }, [theme])
  useEffect(() => {
    const titles = { '/': 'Diet Planet | Agritech & Clean Nutrition', '/processing': 'Farmer Processing | Diet Planet', '/store': 'B2B Bulk Store | Diet Planet', '/tracker': 'Track a Batch | Diet Planet', '/about': 'About Diet Planet | African Food Infrastructure', '/account': 'Farmer Account | Diet Planet' }
    document.title = titles[page] || titles['/']
  }, [page])
  useEffect(() => {
    const handlePopState = () => setPage(window.location.pathname)
    window.addEventListener('popstate', handlePopState)
    return () => window.removeEventListener('popstate', handlePopState)
  }, [])
  const selectedCrop = crops[crop]
  const estimate = useMemo(() => { const weight = Number(mass) || 0; const yieldOutput = Math.round(weight * selectedCrop.rate); const fee = settlement === 'cash' ? weight * selectedCrop.fee : 0; const retained = settlement === 'split' ? Math.round(yieldOutput * 0.75) : yieldOutput; return { yieldOutput, fee, retained } }, [mass, selectedCrop, settlement])
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0)
  const cartTotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 3200) }
  const addToCart = (product) => { setCart((current) => { const found = current.find((item) => item.id === product.id); return found ? current.map((item) => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...product, quantity: 1 }] }); notify(`${product.short} added to wholesale cart`) }
  const updateQuantity = (id, change) => setCart((current) => current.map((item) => item.id === id ? { ...item, quantity: item.quantity + change } : item).filter((item) => item.quantity > 0))
  const submitProcessing = async (event) => { event.preventDefault(); if (!farmer) { setAuthOpen(true); notify('Create a farmer account to save your order history'); return } const token = localStorage.getItem('diet-planet-token'); const response = await fetch('/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ crop, massKg: Number(mass), settlement, location }) }); if (response.ok) { const data = await response.json(); setOrderHistory((current) => [data.order, ...current]); notify(`Order received for ${mass}kg of ${crop}`) } else notify('Could not save the order. Please try again.') }
  const submitAuth = async (event) => { event.preventDefault(); const endpoint = authMode === 'login' ? '/api/auth/login' : '/api/auth/signup'; const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(authForm) }); const data = await response.json(); if (!response.ok) { notify(data.message || 'Authentication failed'); return } localStorage.setItem('diet-planet-token', data.token); localStorage.setItem('diet-planet-farmer', JSON.stringify(data.farmer)); setFarmer(data.farmer); setAuthOpen(false); notify(`Welcome, ${data.farmer.name}`); loadHistory(data.token) }
  const loadHistory = async (token = localStorage.getItem('diet-planet-token')) => { if (!token) return; const response = await fetch('/api/orders', { headers: { Authorization: `Bearer ${token}` } }); if (response.ok) setOrderHistory((await response.json()).orders) }
  useEffect(() => { if (farmer) loadHistory() }, [farmer])
  const signOut = () => { localStorage.removeItem('diet-planet-token'); localStorage.removeItem('diet-planet-farmer'); setFarmer(null); setOrderHistory([]); notify('You have been signed out') }
  const navigate = (path) => { window.history.pushState({}, '', path); setPage(path); setMobileOpen(false); window.scrollTo(0, 0) }
  const pageClass = page === '/' ? 'home-page' : page.replace('/', '') + '-page'

  return (
    <div className={`app-shell ${pageClass}`}>
      <header className="site-header"><button className="brand brand-button" onClick={() => navigate('/')} aria-label="Diet Planet home"><img src={logo} alt="Diet Planet" /></button><nav className={mobileOpen ? 'main-nav open' : 'main-nav'}><button className={page === '/' ? 'active' : ''} onClick={() => navigate('/')}>Home</button><button className={page === '/processing' ? 'active' : ''} onClick={() => navigate('/processing')}>Farmer Processing</button><button className={page === '/store' ? 'active' : ''} onClick={() => navigate('/store')}>B2B Bulk Store</button><button className={page === '/tracker' ? 'active' : ''} onClick={() => navigate('/tracker')}>Track Batch</button><button className={page === '/about' ? 'active' : ''} onClick={() => navigate('/about')}>About Us</button></nav><div className="header-actions"><button className="icon-button theme-toggle" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label="Toggle light and dark mode">{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><button className="account-button" onClick={() => navigate('/account')} aria-label="Open farmer account"><UserRound size={17} /><span>{farmer ? farmer.name.split(' ')[0] : 'Farmer login'}</span></button><button className="cart-button" onClick={() => setCartOpen(true)} aria-label="Open cart"><ShoppingBag size={18} /><span>{cartCount}</span></button><button className="button button-gold header-cta" onClick={() => navigate('/processing')}>Connect / Book Processing <ArrowRight size={16} /></button><button className="icon-button menu-button" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle menu"><Menu size={22} /></button></div></header>
      <main>
        <section className="hero-section" id="home"><div className="hero-copy"><div className="eyebrow"><span className="live-dot" /> THE HARVEST IS OUR STARTING POINT</div><h1>From raw harvest<br />to <em>real nourishment.</em></h1><p className="hero-subtitle">We help farmers turn fresh produce into shelf-stable, high-value nutrition. Better margins for growers. Cleaner staples for everyone.</p><div className="hero-buttons"><button className="button button-gold" onClick={() => navigate('/processing')}>Book Produce Processing <ArrowRight size={17} /></button><button className="button button-outline" onClick={() => navigate('/store')}>Explore Bulk Store <ArrowRight size={17} /></button></div><div className="hero-note"><BadgeCheck size={18} /> Zero upfront cost processing for large-scale farmers</div></div><div className="hero-art"><div className="art-circle" /><div className="art-label label-top">FRESH <span>→</span> FOREVER</div><div className="produce-tile tile-back"><div className="plantain-shape" /></div><div className="produce-tile tile-front"><div className="powder-jar"><span>dp</span></div><div className="jar-label">PLANT<br /><small>POWER</small></div></div><div className="art-stamp"><Sprout size={18} /><span>GROWN<br />WITH<br />PURPOSE</span></div></div></section>
        <section className="stats-strip"><div><strong>2,500<span>+</span></strong><small>TONS PROCESSED</small></div><div><strong>85<span>%</span></strong><small>POST-HARVEST LOSS REDUCED</small></div><div><strong>1,200<span>+</span></strong><small>FARMERS ONBOARDED</small></div><div className="stats-aside">NOURISHING<br /><span>THE NEXT</span><br />GENERATION <ArrowRight size={16} /></div></section>
        <section className="section processing-section" id="processing"><div className="section-heading"><div><div className="eyebrow">01 / FOR FARMERS</div><h2>Your harvest.<br /><em>Worth more.</em></h2></div><p>Our processing model removes the guesswork from post-harvest. See what your crop can become, before you even leave the farm.</p></div><div className="processing-grid"><form className="booking-card" onSubmit={submitProcessing}><div className="card-top"><span className="step-number">01</span><div><h3>Build your processing order</h3><p>Estimate your output in under a minute.</p></div></div><label>SELECT RAW CROP<select value={crop} onChange={(event) => setCrop(event.target.value)}>{Object.keys(crops).map((name) => <option key={name}>{name}</option>)}</select><ChevronDown size={16} /></label><div className="form-row"><label>CROP MASS<div className="input-unit"><input type="number" min="1" value={mass} onChange={(event) => setMass(event.target.value)} /><span>KG</span></div></label><label>DROP-OFF HUB<select value={location} onChange={(event) => setLocation(event.target.value)}><option>Lagos Processing Hub</option><option>Kano Processing Hub</option><option>Ibadan Processing Hub</option></select><ChevronDown size={16} /></label></div><div className="settlement-label">SETTLEMENT MODEL</div><div className="settlement-options"><button type="button" className={settlement === 'split' ? 'settlement selected' : 'settlement'} onClick={() => setSettlement('split')}><span className="radio" /><span><b>25% Produce Split</b><small>Barter · ₦0 upfront</small></span></button><button type="button" className={settlement === 'cash' ? 'settlement selected' : 'settlement'} onClick={() => setSettlement('cash')}><span className="radio" /><span><b>Toll Cash Fee</b><small>Keep 100% of your yield</small></span></button></div><button className="button button-gold full-button" type="submit">Submit Processing Order <ArrowRight size={17} /></button></form><div className="yield-panel"><div className="yield-header"><div><span className="tiny-label">YOUR ESTIMATED OUTPUT</span><h3>{estimate.retained}<span>kg</span></h3><p>of shelf-stable {crop.toLowerCase()}</p></div><div className="yield-icon"><PackageCheck size={26} /></div></div><div className="yield-bar"><span style={{ width: `${Math.min(selectedCrop.rate * 100 * 2.5, 100)}%` }} /></div><div className="yield-stats"><div><span>FRESH INPUT</span><b>{mass || 0} kg</b></div><ArrowRight size={17} /><div><span>PROCESSED YIELD</span><b>{estimate.yieldOutput} kg</b></div></div><div className="shelf-life"><Clock3 size={19} /><div><span>SHELF-LIFE EXPANSION</span><b>From {selectedCrop.days} days <i>to</i> 12 months</b></div></div><div className="cost-row"><span>PROCESSING FEE</span><strong>{settlement === 'split' ? '25% produce split' : `₦${estimate.fee.toLocaleString()}`}</strong></div></div></div></section>
        <section className="section store-section" id="store"><div className="section-heading store-heading"><div><div className="eyebrow">02 / B2B BULK STORE</div><h2>Staples with<br /><em>substance.</em></h2></div><div className="store-tools"><div className="search-box"><Search size={17} /><input placeholder="Search staples" /></div><button className="button button-outline" onClick={() => setCartOpen(true)}><ShoppingBag size={16} /> Cart ({cartCount})</button></div></div><div className="product-grid">{products.map((product) => <article className="product-card" key={product.id}><div className={`product-art ${product.art}`}><span className="product-badge">{product.badge}</span><div className="product-illustration" /></div><div className="product-info"><div><small>{product.category} / BULK READY</small><h3>{product.name}</h3></div><div className="product-bottom"><strong>₦{product.price.toLocaleString()} <small>/ 10kg</small></strong><button className="icon-action" onClick={() => addToCart(product)} aria-label={`Add ${product.name} to cart`}><Plus size={19} /></button></div><div className="weight-row"><span>SELECT BAG SIZE</span><button>10kg</button><button>25kg</button><button>50kg</button></div></div></article>)}</div></section>
        <section className="tracker-section" id="tracker"><div className="tracker-copy"><div className="eyebrow">03 / LIVE BATCH TRACKER</div><h2>Know where your<br /><em>good food is.</em></h2><p>Every batch has a story. Enter your Batch ID to follow yours from our hub to your door.</p><div className="tracker-input"><input value={batchId} onChange={(event) => setBatchId(event.target.value.toUpperCase())} placeholder="Enter Batch ID" /><button onClick={() => notify(`Tracking batch ${batchId}`)}><Search size={18} /></button></div><small className="tracker-hint">Try DP-8829 or your own batch ID</small></div><div className="timeline-card"><div className="timeline-top"><div><span className="live-indicator" /> LIVE STATUS</div><strong>Batch {batchId || '—'}</strong></div><div className="timeline"><div className="timeline-item complete"><span className="timeline-dot"><BadgeCheck size={14} /></span><div><b>Received & Sorted</b><small>Sep 19 · 08:42 AM</small></div></div><div className="timeline-item active"><span className="timeline-dot"><Sprout size={14} /></span><div><b>Dehydrating / Drying</b><small>In progress · Lagos Hub</small></div><span className="pulse-label">NOW</span></div><div className="timeline-item"><span className="timeline-dot" /><div><b>Milling & Packaging</b><small>Up next</small></div></div><div className="timeline-item"><span className="timeline-dot" /><div><b>Quality Tested</b><small>Pending</small></div></div><div className="timeline-item"><span className="timeline-dot" /><div><b>Ready for Pickup</b><small>Pending</small></div></div></div></div></section>
        <section className="trust-band" id="about"><div><ShieldCheck size={24} /><span><b>QUALITY YOU CAN TRACE</b><small>Every batch is lab-tested, sealed, and built for trust.</small></span></div><div><Truck size={24} /><span><b>BUILT FOR BULK</b><small>Reliable supply for retailers, gyms, and kitchens.</small></span></div><div><Sprout size={24} /><span><b>ROOTED IN IMPACT</b><small>More value at the farm gate. Less waste in the world.</small></span></div><article className="about-detail"><div className="eyebrow">ABOUT DIET PLANET</div><h2>Building a stronger<br /><em>food economy.</em></h2><p>Diet Planet is an agritech and clean nutrition platform that helps African farmers move from vulnerable fresh harvests to durable, high-value food products. We coordinate processing, dehydration, milling, packaging, quality control, and bulk distribution so crops can travel further and earn more.</p><p>Our zero-upfront-cost processing model makes industrial post-harvest infrastructure accessible to farmers who are often excluded by cash flow, distance, and fragmented markets. By converting peppers, corn, plantain, cassava, and other staples into shelf-stable powders and flours, we help reduce seasonal waste, stabilize supply, and give families and businesses dependable access to nutritious food.</p><div className="impact-grid"><div><strong>MORE VALUE</strong><span>Kept closer to the farm gate</span></div><div><strong>LESS WASTE</strong><span>More harvest preserved year-round</span></div><div><strong>NEW WORK</strong><span>Jobs across processing and logistics</span></div></div><div className="founder-block"><img src={founderImage} alt="Donald Nnadozie Diala, founder and CEO of Diet Planet" /><div><div className="eyebrow">THE FOUNDER & CEO</div><h3>Donald Nnadozie Diala</h3><p>Donald leads Diet Planet with a practical belief: Africa’s food future will be built by adding value to what the continent already grows. His work connects farmers, processors, retailers, fitness communities, and households around a more resilient nutrition system.</p></div></div></article></section>
        <section className="account-section section" id="account"><div className="section-heading"><div><div className="eyebrow">FARMER ACCOUNT</div><h2>{farmer ? <>Welcome back, {farmer.name.split(' ')[0]}.</> : <>Your harvest<br /><em>has a home.</em></>}</h2></div><p>Keep your processing orders, saved carts, and account details together in one place.</p></div>{farmer ? <div className="account-grid"><div className="account-card"><UserRound size={26} /><h3>{farmer.name}</h3><p>{farmer.phone}</p><button className="button button-outline" onClick={signOut}>Sign out</button></div><div className="account-card history-card"><div className="history-title"><History size={20} /><b>PROCESSING HISTORY</b></div>{orderHistory.length ? orderHistory.map((order) => <div className="history-row" key={order.id}><span>{order.crop}<small>{order.massKg}kg · {order.location || 'Processing hub'}</small></span><strong>{order.status}</strong></div>) : <p className="empty-history">Your saved processing orders will appear here.</p>}</div></div> : <div className="auth-choice"><button className="button button-gold" onClick={() => { setAuthMode('signup'); setAuthOpen(true) }}>Create farmer account <ArrowRight size={17} /></button><button className="button button-outline" onClick={() => { setAuthMode('login'); setAuthOpen(true) }}><LogIn size={16} /> Sign in</button></div>}</section>
      </main>
      <footer className="site-footer"><div className="footer-brand"><button onClick={() => navigate('/')} className="brand brand-button"><img src={logo} alt="Diet Planet" /></button><p>Good food starts at the source.<br />We make sure it goes further.</p></div><div><b>EXPLORE</b><button onClick={() => navigate('/processing')}>For Farmers</button><button onClick={() => navigate('/store')}>Bulk Store</button><button onClick={() => navigate('/tracker')}>Track a Batch</button></div><div><b>CONNECT</b><a href="tel:08082610560">08082610560</a><a href="tel:08082610560">Call Diet Planet</a><span>Lagos, Nigeria</span></div><div className="app-prompt"><b>THE HEALTH APP</b><p>Your better daily, in your pocket.</p><button className="app-button">Download App <ArrowRight size={15} /></button></div><div className="footer-bottom">© 2024 Diet Planet. Nourishment, reimagined. <span>Made for a healthier planet.</span></div></footer>
      {cartOpen && <div className="drawer-backdrop" onClick={() => setCartOpen(false)}><aside className="cart-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow">WHOLESALE ORDER</span><h2>Your cart <span>({cartCount})</span></h2></div><button className="icon-button" onClick={() => setCartOpen(false)} aria-label="Close cart"><X size={21} /></button></div>{cart.length ? <><div className="cart-items">{cart.map((item) => <div className="cart-item" key={item.id}><div className={`mini-art ${item.art}`} /><div className="cart-item-info"><b>{item.short}</b><small>10kg bag · ₦{item.price.toLocaleString()}</small><div className="quantity"><button onClick={() => updateQuantity(item.id, -1)}><Minus size={13} /></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.id, 1)}><Plus size={13} /></button></div></div></div>)}</div><div className="drawer-total"><span>ESTIMATED TOTAL</span><strong>₦{cartTotal.toLocaleString()}</strong></div><button className="button button-gold full-button" onClick={() => { setCartOpen(false); notify('RFQ request started. We will be in touch shortly.') }}>Request a Quote <ArrowRight size={17} /></button><p className="drawer-note">A supply specialist will confirm final pricing, volume, and delivery timeline.</p></> : <div className="empty-cart"><ShoppingBag size={32} /><p>Your wholesale cart is waiting.</p><button className="button button-outline" onClick={() => setCartOpen(false)}>Browse staples</button></div>}</aside></div>}
      {toast && <div className="toast"><BadgeCheck size={18} /> {toast}</div>}
      {authOpen && <div className="drawer-backdrop" onClick={() => setAuthOpen(false)}><form className="auth-modal" onSubmit={submitAuth} onClick={(event) => event.stopPropagation()}><button type="button" className="icon-button auth-close" onClick={() => setAuthOpen(false)} aria-label="Close account form"><X size={20} /></button><div className="eyebrow">DIET PLANET FARMER PORTAL</div><h2>{authMode === 'login' ? 'Welcome back.' : 'Start your farmer account.'}</h2><p>Save orders, build a personal processing record, and keep your wholesale history close.</p>{authMode === 'signup' && <input required placeholder="Full name" value={authForm.name} onChange={(event) => setAuthForm({ ...authForm, name: event.target.value })} /> }<input required placeholder="Phone number" value={authForm.phone} onChange={(event) => setAuthForm({ ...authForm, phone: event.target.value })} /><input required minLength="6" type="password" placeholder="Password" value={authForm.password} onChange={(event) => setAuthForm({ ...authForm, password: event.target.value })} /><button className="button button-gold full-button" type="submit">{authMode === 'login' ? 'Sign in' : 'Create account'} <ArrowRight size={17} /></button><button type="button" className="auth-switch" onClick={() => setAuthMode(authMode === 'login' ? 'signup' : 'login')}>{authMode === 'login' ? 'New here? Create an account' : 'Already registered? Sign in'}</button></form></div>}
    </div>
  )
}

export default App
